
import { Job, JobType, Language, Course, Applicant } from './types';

export const CITY_COORDINATES: Record<string, {lat: number, lng: number, label: string}> = {
  karachi: { lat: 24.8607, lng: 67.0011, label: 'Karachi, Sindh' },
  lahore: { lat: 31.5204, lng: 74.3587, label: 'Lahore, Punjab' },
  islamabad: { lat: 33.6844, lng: 73.0479, label: 'Islamabad, Capital' },
  rawalpindi: { lat: 33.5651, lng: 73.0169, label: 'Rawalpindi, Punjab' },
  faisalabad: { lat: 31.4504, lng: 73.1350, label: 'Faisalabad, Punjab' },
  multan: { lat: 30.1575, lng: 71.5249, label: 'Multan, Punjab' },
  peshawar: { lat: 34.0151, lng: 71.5249, label: 'Peshawar, KPK' },
  quetta: { lat: 30.1798, lng: 66.9750, label: 'Quetta, Balochistan' },
  hyderabad: { lat: 25.3960, lng: 68.3578, label: 'Hyderabad, Sindh' },
  sialkot: { lat: 32.4945, lng: 74.5229, label: 'Sialkot, Punjab' },
  gujranwala: { lat: 32.1877, lng: 74.1945, label: 'Gujranwala, Punjab' },
  sargodha: { lat: 32.0836, lng: 72.6711, label: 'Sargodha, Punjab' },
  bahawalpur: { lat: 29.3544, lng: 71.6911, label: 'Bahawalpur, Punjab' },
  sukkur: { lat: 27.7131, lng: 68.8492, label: 'Sukkur, Sindh' },
  abbottabad: { lat: 34.1688, lng: 73.2215, label: 'Abbottabad, KPK' },
  jhelum: { lat: 32.9405, lng: 73.7276, label: 'Jhelum, Punjab' },
  gwadar: { lat: 25.1216, lng: 62.3254, label: 'Gwadar, Balochistan' },
};

export const MOCK_COURSES: Course[] = [
  { id: '1', title: 'Job Interview Mastery', provider: 'Job Leelo Academy', duration: '45 mins', category: 'Soft Skills', color: 'bg-blue-500' },
  { id: '2', title: 'Basic English for Work', provider: 'Language Center', duration: '2 hours', category: 'Language', color: 'bg-green-500' },
  { id: '3', title: 'Customer Service 101', provider: 'Retail Pro', duration: '1.5 hours', category: 'Sales', color: 'bg-purple-500' },
  { id: '4', title: 'Safety in Factories', provider: 'Safety First', duration: '1 hour', category: 'Technical', color: 'bg-orange-500' },
  { id: '5', title: 'Freelancing Basics', provider: 'DigiSkills', duration: '3 hours', category: 'Tech', color: 'bg-indigo-500' },
  { id: '6', title: 'Mobile Repairing', provider: 'Technical Institute', duration: '10 hours', category: 'Technical', color: 'bg-red-500' },
];

export const MOCK_APPLICANTS: Applicant[] = [
  { id: '1', name: 'Ahmed Ali', role: 'Driver', matchScore: 92, appliedAt: '2h ago', status: 'Pending' },
  { id: '2', name: 'Fatima Bibi', role: 'Receptionist', matchScore: 88, appliedAt: '5h ago', status: 'Shortlisted' },
  { id: '3', name: 'Zainab Khan', role: 'Sales Assistant', matchScore: 75, appliedAt: '1d ago', status: 'Pending' },
  { id: '4', name: 'Bilal Ahmed', role: 'Security Guard', matchScore: 60, appliedAt: '2d ago', status: 'Rejected' },
];

// Massive Verified Job Database
export const MOCK_JOBS: Job[] = [
  // --- INSTAGRAM STYLE / NEW ADDITIONS ---
  {
    id: 'IG1',
    title: 'Social Media Manager (WFH)',
    company: 'Fashion Lounge PK',
    locationName: 'Remote / Lahore',
    salary: 'PKR 40,000',
    type: JobType.PART_TIME,
    postedAt: '1h ago',
    description: 'Looking for a creative female to manage our Instagram page. Must know Canva and Reels editing.',
    requirements: ['Canva', 'Instagram Trends', 'Good English'],
    benefits: ['Work from Home', 'Free Clothes'],
    lat: 31.5204,
    lng: 74.3587,
    isVerified: true,
    category: 'Tech',
    isPremium: true
  },
  {
    id: 'IG2',
    title: 'Online Quran Tutor',
    company: 'Online Academy',
    locationName: 'Remote / Karachi',
    salary: 'PKR 25,000',
    type: JobType.PART_TIME,
    postedAt: '30m ago',
    description: 'Need Qari/Qaria for teaching kids in UK/USA time zone. Good internet required.',
    requirements: ['Tajweed', 'Punctual', 'Zoom/Skype'],
    lat: 24.8607,
    lng: 67.0011,
    isVerified: true,
    category: 'Education'
  },
  {
    id: 'IG3',
    title: 'Female Makeup Artist Assistant',
    company: 'Glam by Sarah',
    locationName: 'DHA Phase 5, Lahore',
    salary: 'PKR 35,000',
    type: JobType.FULL_TIME,
    postedAt: '2h ago',
    description: 'Urgent need for helper in bridal studio. Basic makeup knowledge needed.',
    requirements: ['Female Only', 'Polite', 'Quick Learner'],
    lat: 31.4697,
    lng: 74.4000,
    isVerified: true,
    category: 'Labor'
  },
  {
    id: 'IG4',
    title: 'Content Writer (Freelance)',
    company: 'Tech Blogs',
    locationName: 'Remote / Islamabad',
    salary: 'PKR 2 per word',
    type: JobType.CONTRACT,
    postedAt: '4h ago',
    description: 'Write articles about mobile phones and technology.',
    requirements: ['Good Grammar', 'SEO Basics'],
    lat: 33.6844,
    lng: 73.0479,
    isVerified: false,
    category: 'Tech'
  },
  {
    id: 'IG5',
    title: 'Home Tuition (Math/Physics)',
    company: 'Private Family',
    locationName: 'Bahria Town, Rawalpindi',
    salary: 'PKR 15,000',
    type: JobType.PART_TIME,
    postedAt: '5h ago',
    description: 'Tutor required for Class 9 student. 2 hours daily.',
    requirements: ['MSc/BSc', 'Bike preferred'],
    lat: 33.5651,
    lng: 73.0169,
    isVerified: true,
    category: 'Education'
  },
  {
    id: 'IG6',
    title: 'Shop Helper / Salesman',
    company: 'Mobile Market',
    locationName: 'Hall Road, Lahore',
    salary: 'PKR 25,000',
    type: JobType.FULL_TIME,
    postedAt: '6h ago',
    description: 'Helper needed for mobile accessories shop.',
    requirements: ['Matric', 'Honest'],
    lat: 31.5600,
    lng: 74.3100,
    isVerified: true,
    category: 'Sales'
  },
  {
    id: 'IG7',
    title: 'Wedding Photographer',
    company: 'Studio X',
    locationName: 'Gulshan, Karachi',
    salary: 'PKR 5,000/day',
    type: JobType.DAILY_WAGE,
    postedAt: '1d ago',
    description: 'Need 2nd shooter for wedding event this weekend.',
    requirements: ['Own Camera', 'Event Experience'],
    lat: 24.9300,
    lng: 67.0900,
    isVerified: true,
    category: 'Technical'
  },
  {
    id: 'IG8',
    title: 'Customer Support (Chat)',
    company: 'E-com Store',
    locationName: 'Remote / Faisalabad',
    salary: 'PKR 30,000',
    type: JobType.FULL_TIME,
    postedAt: '2h ago',
    description: 'Reply to customer messages on WhatsApp and Instagram.',
    requirements: ['Typing Speed', 'Patience'],
    lat: 31.4504,
    lng: 73.1350,
    isVerified: true,
    category: 'Office'
  },
  {
    id: 'IG9',
    title: 'Bike Rider for Delivery',
    company: 'Local Pizza Shop',
    locationName: 'Saddar, Rawalpindi',
    salary: 'PKR 28,000',
    type: JobType.FULL_TIME,
    postedAt: '3h ago',
    description: 'Deliver pizza in surrounding areas.',
    requirements: ['Bike', 'License'],
    lat: 33.6000,
    lng: 73.0500,
    isVerified: true,
    category: 'Delivery'
  },
  {
    id: 'IG10',
    title: 'Graphic Designer (Canva)',
    company: 'Marketing Agency',
    locationName: 'Multan',
    salary: 'PKR 35,000',
    type: JobType.FULL_TIME,
    postedAt: '5h ago',
    description: 'Create posts for real estate clients.',
    requirements: ['Canva Pro', 'Creativity'],
    lat: 30.1575,
    lng: 71.5249,
    isVerified: true,
    category: 'Tech'
  },
  {
    id: 'IG11',
    title: 'Female Gym Trainer',
    company: 'Shapes Gym',
    locationName: 'Gulberg, Lahore',
    salary: 'PKR 50,000',
    type: JobType.FULL_TIME,
    postedAt: '1d ago',
    description: 'Trainer for ladies timing 10am to 4pm.',
    requirements: ['Certification', 'Fitness'],
    lat: 31.5100,
    lng: 74.3400,
    isVerified: true,
    category: 'Medical'
  },
  {
    id: 'IG12',
    title: 'Data Entry / Typing',
    company: 'Legal Office',
    locationName: 'Karkhano, Peshawar',
    salary: 'PKR 20,000',
    type: JobType.PART_TIME,
    postedAt: '4h ago',
    description: 'Type legal documents in Urdu/English.',
    requirements: ['InPage', 'MS Word'],
    lat: 34.0000,
    lng: 71.4500,
    isVerified: true,
    category: 'Office'
  },
  {
    id: 'IG13',
    title: 'Caregiver for Elderly',
    company: 'Private Home',
    locationName: 'F-7, Islamabad',
    salary: 'PKR 45,000',
    type: JobType.FULL_TIME,
    postedAt: '6h ago',
    description: 'Need nurse/caregiver for elderly patient. Day shift.',
    requirements: ['Nursing Exp', 'References'],
    lat: 33.7200,
    lng: 73.0500,
    isVerified: true,
    category: 'Medical'
  },
  {
    id: 'IG14',
    title: 'Real Estate Agent',
    company: 'Zameen.com Affiliate',
    locationName: 'DHA, Lahore',
    salary: 'Commission Based',
    type: JobType.CONTRACT,
    postedAt: '2d ago',
    description: 'Sell plots and earn high commission.',
    requirements: ['Sales Skills', 'Transport'],
    lat: 31.4700,
    lng: 74.4500,
    isVerified: true,
    category: 'Sales'
  },
  {
    id: 'IG15',
    title: 'Video Editor (Reels/TikTok)',
    company: 'YouTuber',
    locationName: 'Remote / Karachi',
    salary: 'PKR 30,000',
    type: JobType.PART_TIME,
    postedAt: '1h ago',
    description: 'Edit short engaging videos for TikTok.',
    requirements: ['CapCut', 'Premiere Pro'],
    lat: 24.9000,
    lng: 67.0500,
    isVerified: true,
    category: 'Tech'
  },
  {
    id: 'IG16',
    title: 'Boutique Tailor (Master)',
    company: 'Designer Wear',
    locationName: 'Tariq Road, Karachi',
    salary: 'PKR 60,000',
    type: JobType.FULL_TIME,
    postedAt: '3h ago',
    description: 'Expert cutter and stitcher for ladies designer suits.',
    requirements: ['10 Years Exp', 'Fancy Work'],
    lat: 24.8700,
    lng: 67.0600,
    isVerified: true,
    category: 'Labor'
  },
  {
    id: 'IG17',
    title: 'Tea Boy / Office Boy',
    company: 'Software House',
    locationName: 'Johar Town, Lahore',
    salary: 'PKR 22,000',
    type: JobType.FULL_TIME,
    postedAt: '5h ago',
    description: 'Serve tea, clean office.',
    requirements: ['Honest', 'Clean'],
    lat: 31.4600,
    lng: 74.2900,
    isVerified: true,
    category: 'Helper'
  },
   {
    id: 'IG18',
    title: 'Receptionist (Clinic)',
    company: 'Dental Clinic',
    locationName: 'North Nazimabad, Karachi',
    salary: 'PKR 30,000',
    type: JobType.FULL_TIME,
    postedAt: '1d ago',
    description: 'Manage appointments and patient calls.',
    requirements: ['Polite', 'Computer Basics'],
    lat: 24.9400,
    lng: 67.0400,
    isVerified: true,
    category: 'Medical'
  },
  {
    id: 'IG19',
    title: 'AC Technician Helper',
    company: 'Cool Services',
    locationName: 'Saddar, Hyderabad',
    salary: 'PKR 18,000',
    type: JobType.FULL_TIME,
    postedAt: '4h ago',
    description: 'Helper for AC repair technician.',
    requirements: ['Hardworking'],
    lat: 25.3900,
    lng: 68.3600,
    isVerified: true,
    category: 'Technical'
  },
  {
    id: 'IG20',
    title: 'Voice Over Artist',
    company: 'Ad Agency',
    locationName: 'Remote',
    salary: 'PKR 5,000/project',
    type: JobType.CONTRACT,
    postedAt: '2h ago',
    description: 'Female voice required for radio ad (Urdu).',
    requirements: ['Clear Voice', 'Microphone'],
    lat: 30.0000,
    lng: 70.0000, // Generic location
    isVerified: true,
    category: 'Tech'
  },


  // --- KARACHI ---
  {
    id: 'K1',
    title: 'Factory Worker',
    company: 'Al-Karam Textile Mills',
    locationName: 'Korangi Industrial Area, Karachi',
    salary: 'PKR 35,000',
    type: JobType.FULL_TIME,
    postedAt: '1h ago',
    description: 'Urgent hiring for packaging department. 8-hour shift. Meals provided.',
    requirements: ['Middle/Matric', 'CNIC', 'Physical Fitness'],
    benefits: ['Free Lunch', 'Transport', 'Medical'],
    lat: 24.8387, 
    lng: 67.1218,
    isVerified: true,
    category: 'Labor',
    contactPhone: '03001234567',
    isPremium: true
  },
  {
    id: 'K2',
    title: 'Call Center Agent',
    company: 'Ibex Global',
    locationName: 'Shahrah-e-Faisal, Karachi',
    salary: 'PKR 55,000',
    type: JobType.FULL_TIME,
    postedAt: '3h ago',
    description: 'International campaign. Fluent English required. Night shift.',
    requirements: ['Fluent English', 'Intermediate', 'Night Shift'],
    benefits: ['Pick & Drop', 'Performance Bonus'],
    lat: 24.8632,
    lng: 67.0733,
    isVerified: true,
    category: 'Office',
    isPremium: true
  },
  {
    id: 'K3',
    title: 'Rider / Delivery Boy',
    company: 'FoodPanda',
    locationName: 'Gulshan-e-Iqbal, Karachi',
    salary: 'PKR 45,000',
    type: JobType.CONTRACT,
    postedAt: '20m ago',
    description: 'Own bike required. Earn per delivery.',
    requirements: ['Bike', 'License', 'Smartphone'],
    benefits: ['Flexible Hours', 'Insurance', 'Fuel'],
    lat: 24.9213,
    lng: 67.0970,
    isVerified: true,
    category: 'Delivery'
  },
  {
    id: 'K4',
    title: 'Data Entry Operator',
    company: 'Systems Ltd',
    locationName: 'Clifton, Karachi',
    salary: 'PKR 40,000',
    type: JobType.FULL_TIME,
    postedAt: '5h ago',
    description: 'Excel data entry work. Speed 40wpm required.',
    requirements: ['Excel', 'Typing Speed', 'Intermediate'],
    lat: 24.8138,
    lng: 67.0357,
    isVerified: true,
    category: 'Office'
  },
  {
    id: 'K5',
    title: 'Security Guard',
    company: 'Phoenix Security',
    locationName: 'DHA, Karachi',
    salary: 'PKR 32,000',
    type: JobType.FULL_TIME,
    postedAt: '8h ago',
    description: 'Guard for residential bungalow.',
    requirements: ['Retired Army', 'Weapon License'],
    lat: 24.8050,
    lng: 67.0543,
    isVerified: true,
    category: 'Labor'
  },
  {
    id: 'K6',
    title: 'Receptionist',
    company: 'Aga Khan Hospital',
    locationName: 'Stadium Road, Karachi',
    salary: 'PKR 45,000',
    type: JobType.FULL_TIME,
    postedAt: '4h ago',
    description: 'Front desk officer for evening shift.',
    requirements: ['Graduate', 'Polite', 'Computer Literate'],
    lat: 24.8927,
    lng: 67.0747,
    isVerified: true,
    category: 'Medical'
  },

  // --- LAHORE ---
  {
    id: 'L1',
    title: 'Graphic Designer',
    company: 'NetSol Technologies',
    locationName: 'DHA Phase 6, Lahore',
    salary: 'PKR 70,000',
    type: JobType.FULL_TIME,
    postedAt: '2h ago',
    description: 'Creative designer for social media posts and branding.',
    requirements: ['Photoshop', 'Illustrator', 'Portfolio'],
    benefits: ['Health Insurance', 'Annual Trip'],
    lat: 31.4697,
    lng: 74.4367,
    isVerified: true,
    category: 'Tech',
    isPremium: true
  },
  {
    id: 'L2',
    title: 'Uber/Careem Captain',
    company: 'Uber',
    locationName: 'Model Town, Lahore',
    salary: 'PKR 60,000',
    type: JobType.PART_TIME,
    postedAt: '4h ago',
    description: 'Drive your own car and earn.',
    requirements: ['Car', 'License', 'Clean Record'],
    lat: 31.4882,
    lng: 74.3259,
    isVerified: true,
    category: 'Delivery'
  },
  {
    id: 'L3',
    title: 'Sales Executive',
    company: 'Emporium Mall',
    locationName: 'Johar Town, Lahore',
    salary: 'PKR 35,000',
    type: JobType.FULL_TIME,
    postedAt: '6h ago',
    description: 'Counter sales staff for clothing brand.',
    requirements: ['Good Personality', 'Sales Skills'],
    benefits: ['Commission'],
    lat: 31.4674,
    lng: 74.2662,
    isVerified: true,
    category: 'Sales'
  },
  {
    id: 'L4',
    title: 'Electrician',
    company: 'GharPar',
    locationName: 'Wapda Town, Lahore',
    salary: 'PKR 1,500/day',
    type: JobType.DAILY_WAGE,
    postedAt: '1d ago',
    description: 'Home repair service electrician.',
    requirements: ['Tools', 'Bike', 'Experience'],
    lat: 31.4340,
    lng: 74.2657,
    isVerified: true,
    category: 'Technical'
  },
  {
    id: 'L5',
    title: 'Receptionist',
    company: 'PC Hotel',
    locationName: 'Mall Road, Lahore',
    salary: 'PKR 45,000',
    type: JobType.FULL_TIME,
    postedAt: '2d ago',
    description: 'Guest relations officer.',
    requirements: ['English', 'Presentable'],
    lat: 31.5546,
    lng: 74.3572,
    isVerified: true,
    category: 'Office'
  },
  {
    id: 'L6',
    title: 'Chef De Partie',
    company: 'Salt\'n Pepper',
    locationName: 'Gulberg, Lahore',
    salary: 'PKR 55,000',
    type: JobType.FULL_TIME,
    postedAt: '12h ago',
    description: 'Continental food specialist.',
    requirements: ['Culinary Diploma', '3 Years Experience'],
    lat: 31.5102,
    lng: 74.3441,
    isVerified: true,
    category: 'Food'
  },

  // --- ISLAMABAD / RAWALPINDI ---
  {
    id: 'I1',
    title: 'Nurse',
    company: 'Shifa International Hospital',
    locationName: 'H-8, Islamabad',
    salary: 'PKR 45,000',
    type: JobType.FULL_TIME,
    postedAt: '3h ago',
    description: 'Staff nurse for ICU.',
    requirements: ['Nursing Diploma/Degree', 'PNC Registered'],
    lat: 33.6844,
    lng: 73.0679,
    isVerified: true,
    category: 'Medical'
  },
  {
    id: 'I2',
    title: 'Software Engineer',
    company: 'Techlogix',
    locationName: 'Blue Area, Islamabad',
    salary: 'PKR 150,000',
    type: JobType.FULL_TIME,
    postedAt: '5h ago',
    description: 'Full stack MERN developer.',
    requirements: ['React', 'NodeJS', 'MongoDB'],
    lat: 33.7077,
    lng: 73.0501,
    isVerified: true,
    category: 'Tech',
    isPremium: true
  },
  {
    id: 'R1',
    title: 'Store Keeper',
    company: 'Metro Cash & Carry',
    locationName: 'Airport Road, Rawalpindi',
    salary: 'PKR 30,000',
    type: JobType.FULL_TIME,
    postedAt: '12h ago',
    description: 'Inventory management and stocking.',
    requirements: ['Matric', 'Physical Strength'],
    lat: 33.6146,
    lng: 73.0958,
    isVerified: true,
    category: 'Labor'
  },
  {
    id: 'I3',
    title: 'Driver',
    company: 'Careem',
    locationName: 'G-11, Islamabad',
    salary: 'PKR 35,000',
    type: JobType.CONTRACT,
    postedAt: '1d ago',
    description: 'Office pick and drop.',
    requirements: ['LTV License', '5 Years Exp'],
    lat: 33.6690,
    lng: 73.0040,
    isVerified: true,
    category: 'Labor'
  },

  // --- SIALKOT ---
  {
    id: 'S1',
    title: 'Sports Goods Stitcher',
    company: 'Forward Sports',
    locationName: 'Sialkot Industrial Estate',
    salary: 'PKR 45,000',
    type: JobType.FULL_TIME,
    postedAt: '2d ago',
    description: 'Football stitching expert required.',
    requirements: ['Experience', 'Precision'],
    lat: 32.4945,
    lng: 74.5229,
    isVerified: true,
    category: 'Labor'
  },
  {
    id: 'S2',
    title: 'Export Manager',
    company: 'Surgical Instruments Co',
    locationName: 'Sambrial, Sialkot',
    salary: 'PKR 90,000',
    type: JobType.FULL_TIME,
    postedAt: '1d ago',
    description: 'Manage international shipments and documentation.',
    requirements: ['MBA', 'English', 'Export Docs'],
    lat: 32.4745,
    lng: 74.5029,
    isVerified: true,
    category: 'Office',
    isPremium: true
  },

  // --- GUJRANWALA ---
  {
    id: 'G1',
    title: 'Heavy Machinery Operator',
    company: 'Master Tiles',
    locationName: 'GT Road, Gujranwala',
    salary: 'PKR 40,000',
    type: JobType.FULL_TIME,
    postedAt: '5h ago',
    description: 'Forklift operator.',
    requirements: ['License', 'Safety Awareness'],
    lat: 32.1877,
    lng: 74.1945,
    isVerified: true,
    category: 'Labor'
  },
  {
    id: 'G2',
    title: 'Restaurant Waiter',
    company: 'Bundu Khan',
    locationName: 'Satellite Town, Gujranwala',
    salary: 'PKR 25,000',
    type: JobType.FULL_TIME,
    postedAt: '1d ago',
    description: 'Experienced waiter required.',
    requirements: ['Uniform', 'Manners'],
    lat: 32.1617,
    lng: 74.1883,
    isVerified: true,
    category: 'Food'
  },

  // --- FAISALABAD ---
  {
    id: 'F1',
    title: 'Textile Designer',
    company: 'Sapphire Mills',
    locationName: 'Khurrianwala, Faisalabad',
    salary: 'PKR 65,000',
    type: JobType.FULL_TIME,
    postedAt: '3h ago',
    description: 'Print designer for lawn collection.',
    requirements: ['Textile Degree', 'Digital Printing'],
    lat: 31.4988,
    lng: 73.2084,
    isVerified: true,
    category: 'Tech'
  },
  {
    id: 'F2',
    title: 'Loom Operator',
    company: 'Sitara Textile',
    locationName: 'Sargodha Road, Faisalabad',
    salary: 'PKR 30,000',
    type: JobType.FULL_TIME,
    postedAt: '6h ago',
    description: 'Power loom operator.',
    requirements: ['Experience', 'Night Shift'],
    lat: 31.4504,
    lng: 73.1350,
    isVerified: true,
    category: 'Labor'
  },

  // --- PESHAWAR ---
  {
    id: 'P1',
    title: 'Sales Manager',
    company: 'Toyota Frontier Motors',
    locationName: 'University Rd, Peshawar',
    salary: 'PKR 80,000',
    type: JobType.FULL_TIME,
    postedAt: '1d ago',
    description: 'Showroom sales manager.',
    requirements: ['Automotive Exp', 'Pashto/English'],
    lat: 34.0094,
    lng: 71.4844,
    isVerified: true,
    category: 'Sales'
  },
  {
    id: 'P2',
    title: 'Cook / Chef',
    company: 'Namak Mandi Restaurant',
    locationName: 'Namak Mandi, Peshawar',
    salary: 'PKR 45,000',
    type: JobType.FULL_TIME,
    postedAt: '3h ago',
    description: 'Expert in Karahi and BBQ.',
    requirements: ['Taste Test', 'Hygiene'],
    lat: 34.0150,
    lng: 71.5249,
    isVerified: true,
    category: 'Food'
  },

  // --- QUETTA ---
  {
    id: 'Q1',
    title: 'NGO Coordinator',
    company: 'UNICEF Balochistan',
    locationName: 'Zarghoon Rd, Quetta',
    salary: 'PKR 110,000',
    type: JobType.CONTRACT,
    postedAt: '2h ago',
    description: 'Field coordinator for polio campaign.',
    requirements: ['Masters', 'Local Knowledge'],
    lat: 30.1798,
    lng: 67.0011,
    isVerified: true,
    category: 'Medical',
    isPremium: true
  },
  {
    id: 'Q2',
    title: 'Shop Assistant',
    company: 'Millennium Mall',
    locationName: 'Shahrah-e-Iqbal, Quetta',
    salary: 'PKR 25,000',
    type: JobType.FULL_TIME,
    postedAt: '5h ago',
    description: 'Sales helper for garments shop.',
    requirements: ['Active', 'Honest'],
    lat: 30.1872,
    lng: 67.0125,
    isVerified: true,
    category: 'Sales'
  },

  // --- MULTAN ---
  {
    id: 'M1',
    title: 'Bank Cashier',
    company: 'Meezan Bank',
    locationName: 'Bosan Road, Multan',
    salary: 'PKR 35,000',
    type: JobType.FULL_TIME,
    postedAt: '4h ago',
    description: 'Cash handling and customer service.',
    requirements: ['B.Com', 'Cash Handling'],
    lat: 30.2084,
    lng: 71.4775,
    isVerified: true,
    category: 'Office'
  },
  {
    id: 'M2',
    title: 'Mango Farm Supervisor',
    company: 'Multan Orchards',
    locationName: 'Shujabad Road, Multan',
    salary: 'PKR 40,000',
    type: JobType.FULL_TIME,
    postedAt: '1d ago',
    description: 'Manage mango picking and packaging.',
    requirements: ['Agri Experience', 'Team Lead'],
    lat: 30.1575,
    lng: 71.4249,
    isVerified: true,
    category: 'Labor'
  },

  // --- HYDERABAD ---
  {
    id: 'H1',
    title: 'Medical Rep',
    company: 'GSK',
    locationName: 'Qasimabad, Hyderabad',
    salary: 'PKR 50,000',
    type: JobType.FULL_TIME,
    postedAt: '6h ago',
    description: 'Visit doctors and pharmacies.',
    requirements: ['Bike', 'Pharmacy Degree'],
    lat: 25.3960,
    lng: 68.3578,
    isVerified: true,
    category: 'Sales'
  },
  
  // --- ABBOTTABAD ---
  {
    id: 'A1',
    title: 'Teacher (Science)',
    company: 'Army Burn Hall College',
    locationName: 'Mandian, Abbottabad',
    salary: 'PKR 45,000',
    type: JobType.FULL_TIME,
    postedAt: '1d ago',
    description: 'Physics/Chemistry teacher for O-Levels.',
    requirements: ['MSc', 'Teaching Exp'],
    lat: 34.1688,
    lng: 73.2215,
    isVerified: true,
    category: 'Education'
  },

  // --- SARGODHA ---
  {
    id: 'Sar1',
    title: 'Citrus Farm Manager',
    company: 'Kinnow Exports',
    locationName: 'Sargodha Outskirts',
    salary: 'PKR 60,000',
    type: JobType.FULL_TIME,
    postedAt: '12h ago',
    description: 'Managing kinnow harvest and sorting.',
    requirements: ['Agriculture', 'Management'],
    lat: 32.0836,
    lng: 72.6711,
    isVerified: true,
    category: 'Labor'
  },

  // --- BAHAWALPUR ---
  {
    id: 'B1',
    title: 'Solar Technician',
    company: 'Quaid-e-Azam Solar Park',
    locationName: 'Yazman Road, Bahawalpur',
    salary: 'PKR 55,000',
    type: JobType.FULL_TIME,
    postedAt: '1d ago',
    description: 'Maintenance of solar panels.',
    requirements: ['DAE Electrical', 'Field Work'],
    lat: 29.3544,
    lng: 71.6911,
    isVerified: true,
    category: 'Technical'
  },

  // --- SUKKUR ---
  {
    id: 'Suk1',
    title: 'Warehouse Supervisor',
    company: 'Engro Foods',
    locationName: 'SITE Area, Sukkur',
    salary: 'PKR 45,000',
    type: JobType.FULL_TIME,
    postedAt: '4h ago',
    description: 'Inventory control of dairy products.',
    requirements: ['Graduate', 'Computer'],
    lat: 27.7131,
    lng: 68.8492,
    isVerified: true,
    category: 'Labor'
  },

  // --- JHELUM ---
  {
    id: 'J1',
    title: 'Civil Surveyor',
    company: 'Citi Housing',
    locationName: 'GT Road, Jhelum',
    salary: 'PKR 50,000',
    type: JobType.CONTRACT,
    postedAt: '2d ago',
    description: 'Land surveying for new phase.',
    requirements: ['DAE Civil', 'Total Station'],
    lat: 32.9405,
    lng: 73.7276,
    isVerified: true,
    category: 'Technical'
  },

  // --- GWADAR ---
  {
    id: 'Gw1',
    title: 'Port Crane Operator',
    company: 'Gwadar Port Authority',
    locationName: 'Gwadar Port',
    salary: 'PKR 95,000',
    type: JobType.FULL_TIME,
    postedAt: '3h ago',
    description: 'Heavy crane operation for container loading.',
    requirements: ['Certification', 'Experience'],
    lat: 25.1216,
    lng: 62.3254,
    isVerified: true,
    category: 'Technical',
    isPremium: true
  }
];

export const JOB_CATEGORIES = ['All', 'Labor', 'Sales', 'Delivery', 'Office', 'Helper', 'Tech', 'Medical', 'Education', 'Food', 'Technical'];

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    appTitle: 'Job Leelo',
    tagline: 'Jobs Near Me - Pakistan',
    map: 'Home',
    list: 'List',
    apply: 'One-Tap Apply',
    salary: 'Salary',
    posted: 'Posted',
    verified: 'Verified',
    searchPlaceholder: 'Search jobs, locations...',
    aiMatch: 'AI Match',
    cvBuilder: 'CV Maker',
    postJob: 'Post Job',
    home: 'Home',
    profile: 'Profile',
    selectLang: 'Select Language',
    continue: 'Continue',
    jobDetails: 'Job Details',
    requirements: 'Requirements',
    benefits: 'Benefits',
    description: 'Description',
    generating: 'Generating...',
    applySuccess: 'Application Sent! Good Luck.',
    topMatches: 'Top Matches Today',
    whyMatched: 'Why this matches you:',
    createCV: 'Create CV',
    name: 'Full Name',
    phone: 'Phone Number',
    email: 'Email',
    address: 'Address',
    languages: 'Languages',
    skills: 'Skills',
    experience: 'Experience',
    education: 'Education',
    generateCV: 'Generate CV',
    download: 'Download PDF',
    fraudWarning: 'Safety Tip: Never pay money for a job offer.',
    back: 'Back',
    myLocation: 'Back to Me',
    setupProfile: 'Setup Profile',
    enterName: 'Enter your name',
    selectCategory: 'Preferred Job Category',
    expectedSalary: 'Expected Salary (PKR)',
    startSearching: 'Start Searching',
    filters: 'Filters',
    category: 'Category',
    jobType: 'Job Type',
    partTimeOnly: 'Part Time Only',
    nearMe: 'Jobs Near Me (< 5km)',
    minSalary: 'Min Salary',
    applyFilters: 'Apply Filters',
    clear: 'Clear',
    contactEmployer: 'Contact Employer',
    callNow: 'Call Now',
    jobsApplied: 'Jobs Applied',
    jobsSaved: 'Jobs Saved',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    pakistan: 'Pakistan',
    learn: 'Learn',
    videoResume: 'Video Resume',
    uploadVideo: 'Upload/Record Video (30s)',
    employerMode: 'Switch to Employer Mode',
    seekerMode: 'Switch to Job Seeker Mode',
    dashboard: 'Dashboard',
    applicants: 'Applicants',
    views: 'Views',
    shortlisted: 'Shortlisted',
    premium: 'Premium',
    getVerified: 'Get Verified Badge',
    courses: 'Skill Learning Center',
    startCourse: 'Start Course',
    gender: 'Gender',
    age: 'Age',
    city: 'City',
    educationLevel: 'Education Level',
    shiftPreference: 'Shift Preference',
    hasTransport: 'Do you have your own transport?',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    morning: 'Morning',
    evening: 'Evening',
    night: 'Night',
    any: 'Any',
    matric: 'Matric',
    inter: 'Intermediate',
    bachelors: 'Bachelors',
    masters: 'Masters',
    none: 'None',
    status: 'Status',
    appliedOn: 'Applied On',
    noApplications: 'You have not applied to any jobs yet.',
    statusApplied: 'Applied',
    statusSeen: 'Seen',
    statusShortlisted: 'Shortlisted',
    statusRejected: 'Rejected'
  },
  [Language.URDU]: {
    appTitle: 'جاب لے لو',
    tagline: 'میرے قریب نوکریاں - پاکستان',
    map: 'ہوم',
    list: 'فہرست',
    apply: 'ابھی درخواست دیں',
    salary: 'تنخواہ',
    posted: 'پوسٹ کیا گیا',
    verified: 'تصدیق شدہ',
    searchPlaceholder: 'نوکری یا علاقہ تلاش کریں...',
    aiMatch: 'AI میچ',
    cvBuilder: 'CV بنائیں',
    postJob: 'نوکری لگائیں',
    home: 'ہوم',
    profile: 'پروفائل',
    selectLang: 'زبان منتخب کریں',
    continue: 'جاری رکھیں',
    jobDetails: 'نوکری کی تفصیلات',
    requirements: 'ضروریات',
    benefits: 'فوائد',
    description: 'تفصیل',
    generating: 'تیار ہو رہا ہے...',
    applySuccess: 'درخواست بھیج دی گئی! گڈ لک۔',
    topMatches: 'آج کے بہترین میچز',
    whyMatched: 'یہ آپ کے لیے کیوں موزوں ہے:',
    createCV: 'CV بنائیں',
    name: 'پورا نام',
    phone: 'فون نمبر',
    email: 'ای میل',
    address: 'پتہ',
    languages: 'زبانیں',
    skills: 'مہارتیں',
    experience: 'تجربہ',
    education: 'تعلیم',
    generateCV: 'CV تیار کریں',
    download: 'PDF ڈاؤن لوڈ کریں',
    fraudWarning: 'حفاظتی مشورہ: نوکری کے لیے کبھی پیسے نہ دیں۔',
    back: 'واپس',
    myLocation: 'میری لوکیشن',
    setupProfile: 'پروفائل بنائیں',
    enterName: 'اپنا نام درج کریں',
    selectCategory: 'پسندیدہ نوکری کی قسم',
    expectedSalary: 'توقع شدہ تنخواہ (PKR)',
    startSearching: 'تلاش شروع کریں',
    filters: 'فلٹرز',
    category: 'کیٹیگری',
    jobType: 'نوکری کی قسم',
    partTimeOnly: 'صرف پارٹ ٹائم',
    nearMe: 'قریبی نوکریاں (< 5km)',
    minSalary: 'کم از کم تنخواہ',
    applyFilters: 'فلٹر لگائیں',
    clear: 'صاف کریں',
    contactEmployer: 'مالک سے رابطہ کریں',
    callNow: 'ابھی کال کریں',
    jobsApplied: 'درخواست دی گئی',
    jobsSaved: 'محفوظ شدہ',
    editProfile: 'پروفائل میں ترمیم کریں',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    pakistan: 'پاکستان',
    learn: 'سیکھیں',
    videoResume: 'ویڈیو ریزیومے',
    uploadVideo: 'ویڈیو اپ لوڈ/ریکارڈ کریں',
    employerMode: 'ایمپلائر موڈ',
    seekerMode: 'جاب سیکر موڈ',
    dashboard: 'ڈیش بورڈ',
    applicants: 'امیدوار',
    views: 'ویوز',
    shortlisted: 'شارٹ لسٹ',
    premium: 'پریمیم',
    getVerified: 'تصدیقی بیج حاصل کریں',
    courses: 'سکل سینٹر',
    startCourse: 'کورس شروع کریں',
    gender: 'جنس',
    age: 'عمر',
    city: 'شہر',
    educationLevel: 'تعلیمی قابلیت',
    shiftPreference: 'شفٹ کی ترجیح',
    hasTransport: 'کیا آپ کے پاس سواری ہے؟',
    male: 'مرد',
    female: 'خواتین',
    other: 'دیگر',
    morning: 'صبح',
    evening: 'شام',
    night: 'رات',
    any: 'کوئی بھی',
    matric: 'میٹرک',
    inter: 'انٹر',
    bachelors: 'بیچلرز',
    masters: 'ماسٹرز',
    none: 'کوئی نہیں',
    status: 'اسٹیٹس',
    appliedOn: 'درخواست تاریخ',
    noApplications: 'آپ نے ابھی تک کوئی درخواست نہیں دی۔',
    statusApplied: 'درخواست دی',
    statusSeen: 'دیکھا گیا',
    statusShortlisted: 'شارٹ لسٹ',
    statusRejected: 'مسترد'
  }
};
